kkrt-labs/stwo-brainfuck

- crates/brainfuck_vm/src/bin/brainfuck_vm.rs
- crates/brainfuck_vm/src/compiler.rs
Closes #8 
The test `test_whitespace` verifies that a given Brainfuck code string with various whitespace character (taken from the [Wikipedia article table](https://en.wikipedia.org/wiki/Whitespace_character)) are effectively trimmed (in any place of the code)
> refactor: trim whitespace in compiler only

- crates/brainfuck_vm/src/bin/brainfuck_vm.rs
- crates/brainfuck_vm/src/machine.rs
- crates/brainfuck_vm/src/test_helper.rs
- crates/brainfuck_vm/tests/integration.rs
Should close https://github.com/kkrt-labs/stwo-brainfuck/issues/10
> implement `MachineBuilder`

- crates/brainfuck_prover/src/components/memory/mod.rs
- crates/brainfuck_prover/src/components/memory/table.rs
- crates/brainfuck_prover/src/components/mod.rs
Closes #32 
The field `d` representing the flag for dummy rows is private: `d` must either be 0 or 1 (as a BaseField), which is enforced by the methods `new` and `new_dummy`.
This field `d` appears useless atm, but it'll make more sense once #33 and #34 are done.
> feat: add MemoryTable struct

- crates/brainfuck_prover/src/components/memory/table.rs
> feat: add sort to memory table

- crates/brainfuck_prover/src/components/memory/table.rs
Closes #34 
Following the design choice to enforce correct sorting of the Memory component
> feat: add dummy rows to memory trace

- crates/brainfuck_prover/src/components/io/mod.rs
- crates/brainfuck_prover/src/components/io/table.rs
- crates/brainfuck_prover/src/components/mod.rs
Closes #46, #47 
The unit tests are using a dummy IOTable type, it could be replaced by either InputTable & OutputTable as it doesn't matter.
I feel that duplicating the tests to test for InputTable & OutputTable when the constant parameter doesn't influence the tested method bloats the tests with no added value.
> feat: add IOTable trace

- crates/brainfuck_prover/src/components/instruction/table.rs
Closes #53 
It also includes a small refactor of the instruction table test, moving instructions to a variable as they are used multiple times.
For consistency, I've also done it in the test `test_instruction_table_program_unused_instruction` for both instructions that are used once.
I feel like it is clearer this way: one could read the ci/ni fields and know what the program does, and we clearly see the multiplicity of instructions $m + 1$ where $m$ is the number of times an instruction is executed.
> feat: instruction trace padding

- crates/brainfuck_prover/src/components/memory/table.rs
Implementing the padding made me realize that the `get_row_from_index` method is completely useless
I've refactored `complete_with_dummy_rows` so that it doesn't panic if the memory table is empty, as `pad`.
> refactor: avoid panic on empty memory table when adding dummy rows

- crates/brainfuck_prover/src/components/mod.rs
- crates/brainfuck_prover/src/components/processor/mod.rs
- crates/brainfuck_prover/src/components/processor/table.rs
Should close https://github.com/kkrt-labs/stwo-brainfuck/issues/67
> prover: add `ProcessorTable`

- Cargo.lock
- crates/brainfuck_prover/Cargo.toml
- crates/brainfuck_prover/src/brainfuck_air/mod.rs
- crates/brainfuck_prover/src/components/memory/component.rs
- crates/brainfuck_prover/src/components/memory/mod.rs
- crates/brainfuck_prover/src/components/memory/table.rs
- crates/brainfuck_prover/src/components/mod.rs
Closes #55
The `write_trace` function is in the `table.rs` file to access the private fields of `MemoryTable` and `MemoryTableRow`, but it might be better to refactor it into its own file?
The conversion from `MemoryTable` to `Vec<BaseColumn>` and the evaluation on the circle domain could be refactored into two separate functions, to be used in the `write_trace` function.
The name `write_trace` might be misleading as we're not writing the trace to a tree but simply returning the Trace evaluation and the Claim on its size. (We could add the tree to which the trace evaluation should be written to as parameter and do the write part in this function, it is currently in the `prove_brainfuck` as `tree_builder.extend_evals(trace)`
I'm assuming that trying to convert an empty `MemoryTable` to a …
> feat: add memory trace prove entrypoint

- crates/brainfuck_prover/src/components/memory/component.rs
- crates/brainfuck_prover/src/components/memory/table.rs
Should close https://github.com/kkrt-labs/stwo-brainfuck/issues/74
> memory: implement `MemoryColumn` enum

- crates/brainfuck_prover/src/brainfuck_air/mod.rs
- crates/brainfuck_prover/src/components/memory/component.rs
Closes #72 for good
I've added mocked preprocessed and interaction log size to the Claim of the Memory component, so that the log size of the main trace (now interaction phase 1 while being phase 0 before) is at the right place in the TreeVec
> refactor: constant to preprocessed trace

- .trunk/trunk.yaml
When running `trunk check`, depending on the os/cpu architecture rust would not be properly downloaded (as the previous trunk.yaml rust download only targetted linux)
> fix: use rust system toolchain for trunk check

- .github/workflows/trunk-check.yaml
- .trunk/trunk.yaml
- crates/brainfuck_prover/src/components/memory/table.rs
Having the system version pinned for local use, it requires updating the toolchain in the ci (with `rustup update` before running `trunk check` in the gh action)
> fix: add rust toolchain update to trunk ci

- README.md
- crates/brainfuck_prover/src/components/processor/table.rs
- crates/brainfuck_vm/src/bin/brainfuck_vm.rs
- crates/brainfuck_vm/src/machine.rs
resolving #68 
question 1: i'm not sure which step is handling adding & computing extension columns and also still not sure why we cannot have { }Table to contain full trace including registers + extension columns.
question 2: `ip` should change on padded rows  (base on Alan's tutorial) but our current machine return trace as keep last `ip` to be consistent on followup padded rows - is It expected? also added comment as //TODO for this
> implement `From<Vec<Registers>>` to `ProcessorTable`

- crates/brainfuck_prover/src/brainfuck_air/mod.rs
- crates/brainfuck_prover/src/components/memory/component.rs
- crates/brainfuck_prover/src/components/memory/table.rs
Closes #89, #90
The interaction trace for the Memory components allows proving that the Memory Component main trace is a permutation of the Processor main trace.
Stwo has defined a `relation!` macro to avoid having to implement custom `LookupElements<N>` as we did for `MemoryElements`, but it is a private macro (`pub(crate)`) so we cannot use it for now.
> feat: add interaction trace evaluation

- crates/brainfuck_prover/src/brainfuck_air/mod.rs
Closes #92
We might need to refactor `InteractionClaim` the same way we did for `Claim` in #94
> feat: add interaction trace to prove_brainfuck entrypoint

- crates/brainfuck_prover/src/brainfuck_air/mod.rs
> feat: add memory component to BrainfuckComponents

- crates/brainfuck_prover/src/brainfuck_air/mod.rs
- crates/brainfuck_prover/src/components/memory/table.rs
Refactorization of the Memory table linked to the flattening of the transition constraints into a single row, to avoid bit-reversals.
The Memory component trace is now
| clk | mp | mv | d | next_clk | next_mp | next_mv | next_d |
| --- | --- | --- | --- | --- | --- | --- | --- |
I've chosen to keep the table structure we had as an intermediary representation between `Vec<Registers>` and `MemoryTable`.
| Previously | Refactorization |
| --- | --- |
| `MemoryTableRow` | `MemoryTableEntry`
| `MemoryTable` | `MemoryIntermediateTable`
The `MemoryTableRow` and `MemoryTable` are re-used for the final trace of the memory component.
This way, filling the `clk` jumps with `complete_with_dummy_rows`, the sorting and the padding is done on the `MemoryIntermediateTable`. And we just need to pair the …
> refactor: memory table

- crates/brainfuck_prover/src/brainfuck_air/mod.rs
- crates/brainfuck_prover/src/components/io/table.rs
> feat: add I/O lookup elements

- crates/brainfuck_prover/src/components/io/table.rs
> feat: I/O interaction trace evaluation

- crates/brainfuck_prover/src/brainfuck_air/mod.rs
- crates/brainfuck_prover/src/components/io/component.rs
- crates/brainfuck_prover/src/components/io/table.rs
- crates/brainfuck_prover/src/components/memory/component.rs
- crates/brainfuck_prover/src/components/memory/table.rs
> feat: add IO traces to entrypoints

- crates/brainfuck_prover/src/components/instruction/table.rs
> refactor: add dummy register to flag padding rows

- crates/brainfuck_prover/src/components/program/table.rs
> feat: add Program lookup elements

- crates/brainfuck_prover/src/brainfuck_air/mod.rs
- crates/brainfuck_prover/src/components/program/component.rs
- crates/brainfuck_prover/src/components/program/table.rs
Closes #154,
Closes #157
Closes #159,
Closes #160,
> feat: add Program component constraints

- crates/brainfuck_prover/src/components/processor/component.rs
- crates/brainfuck_prover/src/components/processor/instructions/input_component.rs
- crates/brainfuck_prover/src/components/processor/instructions/jump/jump_if_not_zero_component.rs
- crates/brainfuck_prover/src/components/processor/instructions/jump/jump_if_zero_component.rs
- crates/brainfuck_prover/src/components/processor/instructions/jump/table.rs
- crates/brainfuck_prover/src/components/processor/instructions/left_component.rs
- crates/brainfuck_prover/src/components/processor/instructions/minus_component.rs
- crates/brainfuck_prover/src/components/processor/instructions/output_component.rs
- crates/brainfuck_prover/src/components/processor/instructions/plus_component.rs
- crates/brainfuck_prover/src/components/processor/instructions/right_component.rs
- crates/brainfuck_prover/src/components/processor/instructions/table.rs
- crates/brainfuck_prover/src/components/processor/table.rs
> refactor: trim unused registers from components
