kkrt-labs/stwo-brainfuck

crates/brainfuck_prover/src/components/instruction/table.rs

test: instruction table

---

Cargo.lock
Cargo.toml
crates/brainfuck_prover/Cargo.toml
crates/brainfuck_prover/src/components/memory/table.rs

feat: add From<Vec<Registers>> for MemoryTable

---

crates/brainfuck_prover/src/lib.rs
crates/brainfuck_prover/src/utils/mod.rs

feat: add utils mod for constants needed accross brainfuck_prover

---

crates/brainfuck_prover/src/components/memory/table.rs

feat: pad memory trace to next power of 2

---

crates/brainfuck_prover/src/components/io/table.rs

feat: add padding to I/O trace

---

crates/brainfuck_prover/src/brainfuck_air/mod.rs
crates/brainfuck_prover/src/components/instruction/table.rs
crates/brainfuck_prover/src/components/io/table.rs
crates/brainfuck_vm/src/bin/brainfuck_vm.rs
crates/brainfuck_vm/src/machine.rs
crates/brainfuck_vm/src/test_helper.rs
crates/brainfuck_vm/tests/integration.rs

Closes #75 
Also cleaned up the get_rows method from `IOTable` which is actually unused.

refactor: getters

---

Cargo.lock
Cargo.toml

chore: bump stwo dependency

---

crates/brainfuck_prover/src/components/instruction/table.rs
crates/brainfuck_prover/src/components/io/table.rs
crates/brainfuck_prover/src/components/memory/table.rs
crates/brainfuck_prover/src/components/mod.rs
crates/brainfuck_prover/src/components/processor/table.rs

Should close https://github.com/kkrt-labs/stwo-brainfuck/issues/88

feat: implement the `trace_evaluation`for the `ProcessorTable`

---

crates/brainfuck_prover/src/brainfuck_air/mod.rs

The `verify_brainfuck` has not been refactored along the `prove_brainfuck` one, previously refactored

refactor: refactor verify_brainfuck entrypoint for preprocessed columns

---

crates/brainfuck_prover/src/components/memory/component.rs

feat: scaffold Memory component

---

crates/brainfuck_prover/src/components/instruction/table.rs
crates/brainfuck_prover/src/components/memory/table.rs
crates/brainfuck_prover/src/components/processor/table.rs

refactor: processor table trace

---

crates/brainfuck_prover/src/components/instruction/table.rs
crates/brainfuck_prover/src/components/io/table.rs
crates/brainfuck_prover/src/components/memory/table.rs
crates/brainfuck_prover/src/components/mod.rs
crates/brainfuck_prover/src/components/processor/table.rs

feat: add interaction trace size to TraceColumn

---

crates/brainfuck_prover/src/brainfuck_air/mod.rs
crates/brainfuck_prover/src/components/instruction/table.rs

feat: add instruction lookup elements

---

crates/brainfuck_prover/src/components/processor/component.rs
crates/brainfuck_prover/src/components/processor/mod.rs

feat: scaffold Processor component

---

crates/brainfuck_prover/src/components/instruction/component.rs
crates/brainfuck_prover/src/components/instruction/mod.rs

feat: scaffold Instruction component

---

crates/brainfuck_prover/src/components/instruction/table.rs
crates/brainfuck_prover/src/components/io/table.rs
crates/brainfuck_prover/src/components/processor/table.rs

refactor: add clk and ci registers to IO component

---

crates/brainfuck_prover/src/components/io/component.rs

feat: add IO constraints

---

crates/brainfuck_prover/src/components/instruction/table.rs

fix: instruction table missing program elements in trace

---

crates/brainfuck_prover/src/components/mod.rs
crates/brainfuck_prover/src/components/program/mod.rs
crates/brainfuck_prover/src/components/program/table.rs

feat: add Program table

---

crates/brainfuck_prover/src/components/program/table.rs

feat: add trace evaluation to Program table

---

crates/brainfuck_prover/src/components/program/component.rs
crates/brainfuck_prover/src/components/program/mod.rs

feat: scaffold Program component

---

crates/brainfuck_prover/src/components/program/table.rs

feat: add Program interaction trace evaluation

---

crates/brainfuck_prover/src/brainfuck_air/mod.rs
crates/brainfuck_prover/src/components/instruction/component.rs

Closes #56,
Closes #148,
Closes #149,
Closes #150

feat: add instruction component constraints

---

crates/brainfuck_prover/src/components/processor/table.rs

refactor: add dummy register to flag padding rows of Processor trace

---

crates/brainfuck_prover/src/components/memory/table.rs
crates/brainfuck_prover/src/components/processor/table.rs

feat: add interaction trace evaluation to Processor component

---

Cargo.toml
crates/brainfuck_prover/src/components/instruction/table.rs
crates/brainfuck_prover/src/components/memory/table.rs
crates/brainfuck_prover/src/components/processor/table.rs

- **Upgrade**
- **Add future_not_send lint**
- **Fix some typos**

Some lint config

---

crates/brainfuck_prover/src/brainfuck_air/mod.rs
crates/brainfuck_prover/src/components/instruction/component.rs
crates/brainfuck_prover/src/components/instruction/table.rs
crates/brainfuck_prover/src/components/io/component.rs
crates/brainfuck_prover/src/components/io/table.rs
crates/brainfuck_prover/src/components/memory/component.rs
crates/brainfuck_prover/src/components/memory/table.rs
crates/brainfuck_prover/src/components/mod.rs
crates/brainfuck_prover/src/components/processor/component.rs
crates/brainfuck_prover/src/components/processor/table.rs
crates/brainfuck_prover/src/components/program/component.rs
crates/brainfuck_prover/src/components/program/table.rs

refactor: refactor InteractionClaim to a common struct for all components

---

crates/brainfuck_prover/src/components/processor/component.rs
crates/brainfuck_prover/src/components/processor/table.rs

feat: add processor component constraints

---

crates/brainfuck_prover/src/components/mod.rs
crates/brainfuck_prover/src/components/processor/instructions/mod.rs
crates/brainfuck_prover/src/components/processor/instructions/table.rs
crates/brainfuck_prover/src/components/processor/mod.rs

feat: add processor instruction table

---

crates/brainfuck_prover/src/components/processor/instructions/mod.rs
crates/brainfuck_prover/src/components/processor/instructions/plus_component.rs

feat: add plus instruction component

---

crates/brainfuck_prover/src/components/processor/instructions/minus_component.rs
crates/brainfuck_prover/src/components/processor/instructions/mod.rs

feat: add minus instruction component

---

crates/brainfuck_prover/src/components/processor/instructions/mod.rs
crates/brainfuck_prover/src/components/processor/instructions/right_component.rs

feat: add shift right instruction component

---

crates/brainfuck_prover/src/components/mod.rs
crates/brainfuck_prover/src/components/processor/instructions/jump/jump_if_not_zero_component.rs
crates/brainfuck_prover/src/components/processor/instructions/jump/jump_if_zero_component.rs
crates/brainfuck_prover/src/components/processor/instructions/jump/mod.rs
crates/brainfuck_prover/src/components/processor/instructions/jump/table.rs
crates/brainfuck_prover/src/components/processor/instructions/mod.rs

feat: add jump components

---

crates/brainfuck_prover/src/components/mod.rs
crates/brainfuck_prover/src/components/processor/instructions/end_of_execution/component.rs
crates/brainfuck_prover/src/components/processor/instructions/end_of_execution/mod.rs
crates/brainfuck_prover/src/components/processor/instructions/end_of_execution/table.rs
crates/brainfuck_prover/src/components/processor/instructions/mod.rs

feat: add end of execution component

---

crates/brainfuck_prover/src/components/instruction/component.rs
crates/brainfuck_prover/src/components/instruction/table.rs
crates/brainfuck_prover/src/components/memory/component.rs
crates/brainfuck_prover/src/components/memory/table.rs

Update comments on already implemented  components and related tables.

chore: update various comments

---

crates/brainfuck_prover/src/brainfuck_air/mod.rs

Closes #87
Closes #145
Closes #146
Closes #173
Closes #203

feat: add components to prove entrypoint

---

.github/workflows/ci.yaml
Cargo.lock
Cargo.toml
crates/brainfuck_prover/src/brainfuck_air/mod.rs
crates/brainfuck_prover/src/components/instruction/component.rs
crates/brainfuck_prover/src/components/memory/component.rs
crates/brainfuck_prover/src/components/processor/component.rs
crates/brainfuck_prover/src/components/processor/instructions/end_of_execution/component.rs
crates/brainfuck_prover/src/components/processor/instructions/input_component.rs
crates/brainfuck_prover/src/components/processor/instructions/jump/jump_if_not_zero_component.rs
crates/brainfuck_prover/src/components/processor/instructions/jump/jump_if_zero_component.rs
crates/brainfuck_prover/src/components/processor/instructions/left_component.rs
crates/brainfuck_prover/src/components/processor/instructions/minus_component.rs
crates/brainfuck_prover/src/components/processor/instructions/output_component.rs
crates/brainfuck_prover/src/components/processor/instructions/plus_component.rs
crates/brainfuck_prover/src/components/processor/instructions/right_component.rs
crates/brainfuck_prover/src/components/processor/instructions/table.rs
crates/brainfuck_prover/src/components/processor/table.rs
crates/brainfuck_prover/src/components/program/component.rs
crates/brainfuck_prover/src/lib.rs
crates/brainfuck_vm/src/machine.rs
rust-toolchain.toml

chore: update stwo

---

README.md
crates/brainfuck_prover/src/bin/brainfuck_prover.rs

doc: update readme

---

crates/brainfuck_prover/src/brainfuck_air/mod.rs

refactor: add const fn for preprocessed column log sizes
